image: ruby:3.0.1

services:
  - postgres:latest

variables:
  POSTGRES_DB: lago_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

cache:
  paths:
    - vendor/ruby

before_script:
  - ruby -v 
  - bundle config set path 'vendor'
  - bundle install -j $(nproc)

rspec:
  variables:
    RAILS_ENV: test
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  script:
    - bundle exec rake db:migrate
    - bundle exec rspec
