default: &default
  adapter: postgresql

development:
  <<: *default
  host: localhost
  username: lago
  password: changeme
  database: lago
  port: 5432

test:
  <<: *default
  database: lago

production:
  <<: *default
  database: lago
