name: Deploy Preview to Staging
on: workflow_dispatch
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    env:
      PORTER_HOST: https://dashboard.getporter.dev
      PORTER_CLUSTER: ${{ secrets.PORTER_CLUSTER }}
      PORTER_PROJECT: ${{ secrets.PORTER_PROJECT }}
      PORTER_TOKEN: ${{ secrets.PORTER_TOKEN_2643 }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4
    - name: Set current folder
      id: current_folder
      run: echo "::set-output name=folder::$(pwd)"
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Replace Variables in values.yaml
      env:
        ECR_REPOSITORY: ${{ steps.login-ecr.outputs.registry }}/lago-api-staging
        BRANCH: ${{ steps.extract_branch.outputs.branch }}
        DATABASE_URL: postgres://lago:${{ secrets.DB_STAGING_PASSWORD }}@${{ secrets.DB_STAGING_HOST}}:5432/${{ steps.extract_branch.outputs.branch }}
      run: |
        sudo apt update && sudo apt install -y gettext
        envsubst < ./porter/values.yaml > ./porter/env_values.yaml
    - name: Install Porter
      run: |
        cd /tmp
        /bin/bash -c "$(curl -fsSL https://install.porter.run/)"
    - name: Get back to working directory
      run: cd ${{ steps.current_folder.outputs.folder }}
    - name: Check if preview exists
      id: preview_exists
      run: echo "::set-output name=exists::$(porter get ${{ steps.extract_branch.outputs.branch }}-api &> /dev/null && echo 'true' || echo 'false')"
    - name: Update Porter app
      if: ${{ steps.preview_exists.outputs.exists == 'true' }}
      uses: porter-dev/porter-cli-action@v0.1.0
      with:
        command: update --app ${{ steps.extract_branch.outputs.branch}}-api --values ./porter/env_values.yaml --source registry --tag {{ steps.extract_branch.outputs.branch }}
    - name: Create Porter app
      if: ${{ steps.preview_exists.outputs.exists == 'false' }}
      uses: porter-dev/porter-cli-action@v0.1.0
      with:
        command: create web --app ${{ steps.extract_branch.outputs.branch}}-api --values ./porter/env_values.yaml --tag {{ steps.extract_branch.outputs.branch }}
